server:
  port: 8087
spring:
  application:
    name: sales-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sales
    username: sales
    password: sales
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update